INSERT INTO Categoria(Id, Nome, Descricao)
VALUES
(80,	"Artes e entretenimento",	"Acessórios para instrumentos musicais e orquestras	"),
(81,	"Artes e entretenimento",	"Arte e artesanato"),
(82,	" Artes e entretenimento",	"Arte e artesanato"),
(83,	"Artes e entretenimento",	"Instrumentos musicais"),
(84,	"Artigos esportivos",		"Caça e tiro"),
(85,	"Materiais de escritório",	"Instrumentos de escrita"),
(86,	"Saúde e beleza",			" Cosméticos"),
(87,	"Saúde e beleza",			"Cosméticos");


INSERT INTO Produto(Id, Nome,	Descricao,	Preco,	CategoriaId)
VALUES
(36,	RTRIM("Manutenção e limpeza de clarinete"),				RTRIM("Escovas de limpeza para clarinete"),	4817.0,	80),
(37,	RTRIM("Manutenção e limpeza de clarinete"),				RTRIM("Escovas de limpeza para clarinete"),	890.0,	80),
(38,	RTRIM("Manutenção e limpeza de clarinete"),				RTRIM("Escovas de limpeza para clarinete"),	9998.0,	80),
(39,	RTRIM("Manutenção e limpeza de clarinete"),				RTRIM("Escovas de limpeza para clarinete"),	7319.0,	80),
(40,	RTRIM("Manutenção e limpeza de clarinete"),				RTRIM("Kits de manutenção para clarinete"),	6603.0,	80),
(41,	RTRIM("Manutenção e limpeza de clarinete"),				RTRIM("Protetores de sapatilhas para clarinete"),	1055.0,	80),
(42,	RTRIM("Peças para clarinete"),							RTRIM("Barriletes para clarinete"),	5465.0,	80),
(43,	RTRIM("Peças para clarinete"),							RTRIM("Boquilhas para clarinete"),	4159.0,	80),
(44,	RTRIM("Peças para clarinete"),							RTRIM("Campânulas para clarinete"),	4399.0,	80),
(45,	RTRIM("Peças para clarinete"),							RTRIM("Peças pequenas para clarinete"),	9519.0,	80),
(46,	RTRIM("Manutenção e limpeza de fagote"),				RTRIM("Escovas de limpeza para fagote"),	4399.0,	80),
(47,	RTRIM("Peças para fagote"),								RTRIM("Boquilhas para fagote"),	3437.0,	80),
(48,	RTRIM("Peças para fagote"),								RTRIM("Peças pequenas para fagote"),	3989.0,	80),
(49,	RTRIM("Manutenção e limpeza de flauta"),				RTRIM("Escovas de limpeza para flauta"),	9630.0,	80),
(50,	RTRIM("Manutenção e limpeza de flauta"),				RTRIM("Kits de manutenção para flauta"),	6186.0,	80),
(51,	RTRIM("Manutenção e limpeza de flauta"),				RTRIM("Varetas de limpeza para flauta"),	2038.0,	80),
(52,	RTRIM("Peças para flauta"),								RTRIM("Bocais para flauta"),	1632.0,	80),
(53,	RTRIM("Peças para flauta"),								RTRIM("Peças pequenas para flauta"),	2047.0,	80),
(54,	RTRIM("Manutenção e limpeza de oboé"),					RTRIM("Escovas de limpeza para oboé"),	5336.0,	80),
(55,	RTRIM("Manutenção e limpeza de oboé"),					RTRIM("Kits de manutenção para oboé"),	542.0,	80),
(56,	RTRIM("Peças para oboé"),								RTRIM("Peças pequenas para oboé"),	6698.0,	80),
(57,	RTRIM("Manutenção e limpeza de saxofone"),				RTRIM("Escovas de limpeza para saxofone"),	1863.0,	80),
(58,	RTRIM("Manutenção e limpeza de saxofone"),				RTRIM("Kits de manutenção para saxofone"),	9221.0,	80),
(59,	RTRIM("Manutenção e limpeza de saxofone"),				RTRIM("Protetores de sapatilhas para saxofone"),	515.0,	80),
(60,	RTRIM("Peças para saxofone"),							RTRIM("Boquilhas para saxofone"),	4914.0,	80),
(61,	RTRIM("Peças para saxofone"),							RTRIM("Correias de pescoço para saxofone"),	3022.0,	80),
(62,	RTRIM("Peças para saxofone"),							RTRIM("Peças pequenas para saxofone"),	368.0,	80),
(63,	RTRIM("Massa em argila e para modelagem"),				RTRIM("Argila"),	2772.0,	81),
(64,	RTRIM("Massa em argila e para modelagem"),				RTRIM("Massa de modelar"),	2758.0,	81),
(65,	RTRIM("Cartolinas e papel para scrapbooking"),			RTRIM("Cardstock"),	5474.0,	81),
(66,	RTRIM("Cartolinas e papel para scrapbooking"),			RTRIM("Papel para scrapbook"),	9093.0,	81),
(67,	RTRIM("Telas para artesanato"),							RTRIM("Telas de plástico"),	9044.0,	81),
(68,	RTRIM("Telas para artesanato"),							RTRIM("Telas para bordado"),	7941.0,	81),
(69,	RTRIM("Telas para artesanato"),							RTRIM("Telas para pintura"),	2571.0,	82),
(70,	RTRIM("Tambores de mão"),								RTRIM("Bongôs"),	9032.0,	83),
(71,	RTRIM("Tambores de mão"),								RTRIM("Cajóns"),	7446.0,	83),
(72,	RTRIM("Tambores de mão"),								RTRIM("Congas"),	136.0,	83),
(73,	RTRIM("Tambores de mão"),								RTRIM("Djembês"),	8338.0,	83),
(74,	RTRIM("Tambores de mão"),								RTRIM("Tablas"),	1284.0,	83),
(75,	RTRIM("Tambores de mão"),								RTRIM("Tambor falante"),	1404.0,	83),
(76,	RTRIM("Tambores de mão"),								RTRIM("Tamborins"),	3166.0,	83),
(77,	RTRIM("Acessórios e peças para armas de pressão	"),		RTRIM("Baterias para armas de pressão"),	1621.0,	84),
(78,	RTRIM("Peças de armas de paintball"),					RTRIM("Cano da arma de paintball"),	8603.0,	84),
(79,	RTRIM("Peças de armas de paintball"),					RTRIM("Compartimento de paintball"),	8155.0,	84),
(80,	RTRIM("Peças de armas de paintball"),					RTRIM("Conectores drop forward para armas de paintball")	 ,  4963.0,	84),
(81,	RTRIM("Peças de armas de paintball"),					RTRIM("Tanques de CO2 de paintball"),	349.0,	84),
(82,	RTRIM("Lápis para escrever"),							RTRIM("Lapiseiras"),	6855.0,	85),
(83,	RTRIM("Lápis para escrever"),							RTRIM("Lápis de madeira"),	3229.0,	85),
(84,	RTRIM("Acessórios para cílios"),						RTRIM("postiços	Aplicadores para cílios postiços"),	5579.0,	86),
(85,	RTRIM("Acessórios para cílios"),						RTRIM("postiços	Cola para cílios postiços"),	8208.0,	87),
(86,	RTRIM("Acessórios para cílios"),						RTRIM("postiços	Removedor de cílios postiços"),	4303.0,	87);



